### ISSUE TITLE
Is spl-token 3.3.0 a must?

### ISSUE THREAD

**Issue by dovahcrow** [saber-hq/stable-swap#137]
https://github.com/saber-hq/stable-swap/blob/master/stable-swap-client/Cargo.toml#L21 this line restricts spl-token to be 3.3.0 or above, but solana-account-decoder is forcing spl-token to be 3.2 https://github.com/solana-labs/solana/blob/master/account-decoder/Cargo.toml#L25.

This means this repo is not possible to be used with solana-account-decoder until they bump the version.

**Comment by michaelhly** [comment]
I think we should bump the spl-token dependency in https://github.com/solana-labs/solana/blob/master/account-decoder/Cargo.toml#L25.

**Comment by macalinao** [comment]
@dovahcrow feel free to send a PR to change this to `^3`.

**Comment by dovahcrow** [comment]
@macalinao they said they are gonna upgrade to 3.3 soon, so maybe we can wait for them? https://github.com/solana-labs/solana/pull/23570

**Comment by michaelhly** [comment]
Addressed by https://github.com/saber-hq/stable-swap/commit/0476964cb7ba5d533e7c2a9a808cfdce3f906107
