### ISSUE TITLE
Question: test coverage/strategy

### ISSUE THREAD

**Issue by Synesso** [saber-hq/stable-swap#74]
Hi. Just doing a quick sanity check of the repo for someone before they use the product. Lots of good stuff here. The test coverage seems limited to serialisation code, IIUC. Is that right? Are there tests somewhere for the core swap functionality and for staking? In some other repo, maybe?

**Comment by michaelhly** [comment]
Currently, this repo only contains rust client code and math helpers we published for people to use and build on top of Saber.

Check out the [archive](https://github.com/saber-hq/stable-swap/tree/archive) branch for some old references.

**Comment by michaelhly** [comment]
Addressed in https://github.com/saber-hq/stable-swap/pull/101
